### PR TITLE
Android fix

### PR DESCRIPTION
**Pull request by edewit**
Changed to use the newer google play location service and removed the deprecated method usage, in doing so changed the api a bit the register now takes a function instead of a string parameter:

instead of:
```js
geofencing.register({
  callback: 'app.onGeofenceEvent'
});
```
one should now call:
```js
geofencing.register(app.onGeofenceEvent);
```

### CODE REVIEW

**Comment by edewit** [comment]
fixing issue [AGCORDOVA-85](https://issues.jboss.org/browse/AGCORDOVA-85)

**Comment by matzew** [comment]
@danielpassos or @secondsun any thoughts?

**Comment by danielpassos** [comment]
@edewit We have some cookbook app to test it?

**Comment by edewit** [comment]
there is a crude example that ships with the plugin, but could make something a bit more user friendly. I've created an [issue to track this](https://issues.jboss.org/browse/AGCORDOVA-95)

**Comment by danielpassos** [comment]
I'm trying test it using example app but i'm getting:

```
W/System.err( 3428): java.lang.ClassNotFoundException: org.apache.cordova.whitelist.WhitelistPlugin
W/System.err( 3428): 	at java.lang.Class.classForName(Native Method)
W/System.err( 3428): 	at java.lang.Class.forName(Class.java:308)
W/System.err( 3428): 	at java.lang.Class.forName(Class.java:272)
W/System.err( 3428): 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:487)
W/System.err( 3428): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:167)
W/System.err( 3428): 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:95)
W/System.err( 3428): 	at org.apache.cordova.PluginManager.init(PluginManager.java:84)
W/System.err( 3428): 	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
W/System.err( 3428): 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:138)
W/System.err( 3428): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:209)
W/System.err( 3428): 	at io.cordova.hellocordova.MainActivity.onCreate(MainActivity.java:32)
W/System.err( 3428): 	at android.app.Activity.performCreate(Activity.java:5933)
W/System.err( 3428): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
W/System.err( 3428): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
W/System.err( 3428): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
W/System.err( 3428): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
W/System.err( 3428): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
W/System.err( 3428): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 3428): 	at android.os.Looper.loop(Looper.java:135)
W/System.err( 3428): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
W/System.err( 3428): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 3428): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 3428): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/System.err( 3428): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/System.err( 3428): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.cordova.whitelist.WhitelistPlugin" on path: DexPathList[[zip file "/data/app/io.cordova.hellocordova-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
``` 

What I did?

```shell
cordova create agt
cd agt/www
rm index.html
wget https://raw.githubusercontent.com/aerogear/aerogear-cordova-geo/master/example/index.html
cd ..
cordova platform add android
cordova run android --device
```

**Comment by edewit** [comment]
Did you see the Whitelist plugin get added when you did `cordova platform add android`? The whitelist plugin is a new plugin that gets automatically added.

**Comment by danielpassos** [comment]
Yes :/

```
→ cordova plugin list
android.support.v4 1.0.0 "Android Support v4"
com.google.playservices 19.0.0 "Google Play Services for Android"
cordova-plugin-whitelist 1.0.0 "Whitelist"
org.jboss.aerogear.cordova.geo 0.0.1 "AeroGear Geo Plugin"
```

**Comment by edewit** [comment]
don't know what is going on, could you try and remove and add the platform again

**Comment by danielpassos** [comment]
Same problem. I give up!

**Comment by lholmquist** [comment]
lets me give this a go real quick

**Comment by lholmquist** [comment]
doing these 3 steps:

`cordova create agt`

`cordova platform add android`

`cordova plugin add https://github.com/edewit/aerogear-geo-cordova.git\#android-fix`

returns:  https://gist.github.com/lholmquist/bc96e6702d58dcae282b


`cordova plugin list`

    android.support.v4 1.0.0 "Android Support v4"
    com.google.playservices 19.0.0 "Google Play Services for Android"
    org.jboss.aerogear.cordova.geo 0.0.1 "AeroGear Geo Plugin"


do not see that whitelist plugin

**Comment by lholmquist** [comment]
running a `cordova run android` i am able to get it to run and build succesfully on my Galaxy

using cordova 4.2.0

**Comment by lholmquist** [comment]
i just update to cordova 5.0.0 and ran the same steps, both adding the plugin first and also adding the platform first.

both ways added the whitelist plugin.   but i had no issues build and putting it on my device

**Comment by abstractj** [comment]
@passos

**Comment by abstractj** [comment]
I will give it a try tomorrow in the early morning after talk with @danielpassos and later we can merge.

**Comment by danielpassos** [comment]
```
sudo npm uninstall cordova -g
sudo npm install -g cordova
```

And it started works :/

:+1:

**Pull request merged**
